"""CSV metadata system for CallMeTK OS."""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Iterable

from .naming import NamingRecord, validate_ctk_id, validate_slug

CSV_COLUMNS = [
    "ctk_id",
    "name",
    "slug",
    "type",
    "created",
    "status",
    "source_path",
    "tags",
    "notes",
]

REQUIRED_COLUMNS = ["ctk_id", "name", "slug", "type", "created", "status"]


def blank_row(record: NamingRecord, source_path: str = "", tags: str = "", notes: str = "") -> dict[str, str]:
    return {
        "ctk_id": record.ctk_id,
        "name": record.name,
        "slug": record.slug,
        "type": record.type,
        "created": record.created,
        "status": record.status,
        "source_path": source_path,
        "tags": tags,
        "notes": notes,
    }


def write_csv(path: Path, rows: Iterable[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in CSV_COLUMNS})


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def validate_csv(path: Path) -> list[str]:
    errors: list[str] = []
    if not path.exists():
        return [f"CSV not found: {path}"]
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        columns = reader.fieldnames or []
        for col in REQUIRED_COLUMNS:
            if col not in columns:
                errors.append(f"Missing required column: {col}")
        for index, row in enumerate(reader, start=2):
            ctk_id = row.get("ctk_id", "")
            slug = row.get("slug", "")
            if not validate_ctk_id(ctk_id):
                errors.append(f"Row {index}: invalid ctk_id '{ctk_id}'")
            if not validate_slug(slug):
                errors.append(f"Row {index}: invalid slug '{slug}'")
            for col in REQUIRED_COLUMNS:
                if not row.get(col, "").strip():
                    errors.append(f"Row {index}: missing value for {col}")
    return errors


def create_project_metadata(path: Path, project_type: str, name: str) -> dict[str, str]:
    record = NamingRecord.create(project_type, name)
    row = blank_row(record, notes="Generated by CallMeTK OS")
    write_csv(path, [row])
    return row
